modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="noe"
version="1.2.2"
displayName="NOE"
displayURL="https://mcreator.net"
credits="Pour le serveur N.O.E"
authors="imnowa"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.noe]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.noe]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration
